document.write('	<div id="snSiblingCategory">'
+'		<h2>このカテゴリーから探す</h2>'
+'		<dl>'
+'			<dt id="cLag"><a href="#">ラグ・クッション<span>戻る</span></a></dt>'
+'			<dd><a href="#">カーディガン・ベスト</a></dd>'
+'			<dd><span class="current">セーター <span>(24)</span></span></dd>'
+'			<dd><a href="#">トレーナー・パーカー <span>(24)</span></a></dd>'
+'			<dd><a href="#">シャツ <span>(24)</span></a></dd>'
+'			<dd><a href="#">ワンピース・チュニック <span>(24)</span></a></dd>'
+'			<dd><a href="#">ジャケット・コート <span>(24)</span></a></dd>'
+'			<dd><a href="#">スカート・パンツ <span>(24)</span></a></dd>'
+'			<dd><a href="#">Fitness &amp; yoga <span>(24)</span></a></dd>'
+'			<dd><a href="#">MUJI LABO <span>(24)</span></a></dd>'
+'			<dd><a href="#">ビジネスウェア <span>(24)</span></a></dd>'
+'			<dd><a href="#">インナーウェア・肌着 <span>(24)</span></a></dd>'
+'			<dd><a href="#">ブラジャー <span>(24)</span></a></dd>'
+'			<dd><a href="#">ショーツ <span>(24)</span></a></dd>'
+'		</dl>'
+'	</div><!-- /#snSiblingCategory -->'
+'	<div id="snCategory">'
+'		<h2>全商品カテゴリー</h2>'
+'		<div id="snCategoryList">（<a href="/store/pc/user/notice/category_list.jsp">一覧</a>）</div>'
+'		<ul>'
+'			<li class="D00010"><h3>今が旬</h3>'
+'				<ul>'
+'					<li><a href="#">キャンペーン／特集一覧</a></li>'
+'					<li><a href="#">新発売商品</a></li>'
+'					<li><a href="#">ネットストア限定商品</a></li>'
+'				</ul>'
+'			</li>'
+'			<li class="D00011"><h3>お買い得</h3>'
+'				<ul>'
+'					<li><a href="#">アウトレット</a></li>'
+'					<li><a href="#">まとめ買い</a></li>'
+'					<li><a href="#">季節の品のお買い得</a></li>'
+'					<li><a href="#">価格を見直しました</a></li>'
+'				</ul>'
+'			</li>'
+'			<li class="D00001"><h3>衣料品</h3>'
+'				<ul>'
+'					<li><a href="/store/cmdty/section/T10000">婦人ウェア</a></li>'
+'					<li><a href="/store/cmdty/section/T10001">婦人インナーウェア</a></li>'
+'					<li><a href="/store/cmdty/section/T10002">紳士ウェア</a></li>'
+'					<li><a href="/store/cmdty/section/T10003">紳士インナーウェア</a></li>'
+'					<li><a href="/store/cmdty/section/T10004">靴</a></li>'
+'					<li><a href="/store/cmdty/section/T10005">バッグ</a></li>'
+'					<li><a href="/store/cmdty/section/T10006">服飾雑貨</a></li>'
+'				</ul>'
+'			</li>'
+'			<li class="D00002"><h3>子供・マタニティ</h3>'
+'				<ul>'
+'					<li><a href="#">ベビー（80〜110）</a></li>'
+'					<li><a href="#">トドラー（110〜130）</a></li>'
+'					<li><a href="#">マタニティ・新生児</a></li>'
+'					<li><a href="#">子供用品・家具</a></li>'
+'				</ul>'
+'			</li>'
+'			<li class="D00003"><h3>家具・インテリア</h3>'
+'				<ul>'
+'					<li><a href="#">ベッド</a></li>'
+'					<li><a href="#">ソファ</a></li>'
+'					<li><a href="#">収納家具</a></li>'
+'					<li><a href="#">収納用品</a></li>'
+'					<li><a href="#">ユニットシェルフ</a></li>'
+'					<li><a href="#">テーブル・チェア</a></li>'
+'					<li><a href="#">デスク・チェア</a></li>'
+'					<li><a href="#">インテリア用品・本</a></li>'
+'					<li><a href="#">寝具</a></li>'
+'					<li><a href="#">カーテン・ブラインド</a></li>'
+'					<li><a href="#">ラグ・クッション</a></li>'
+'					<li><a href="#">スリッパ・タオル</a></li>'
+'					<li><a href="#">家電・照明</a></li>'
+'				</ul>'
+'			</li>'
+'			<li class="D00004"><h3>生活雑貨</h3>'
+'				<ul>'
+'					<li><a href="#">キッチン用品・食器</a></li>'
+'					<li><a href="#">エプロン・キッチンマット</a></li>'
+'					<li><a href="#">文房具・アルバム</a></li>'
+'					<li><a href="#">化粧品・ケア用品</a></li>'
+'					<li><a href="#">アロマ・フレグランス</a></li>'
+'					<li><a href="#">ポーチ・ケース</a></li>'
+'					<li><a href="#">バス・トイレ</a></li>'
+'					<li><a href="#">掃除・洗濯用品</a></li>'
+'					<li><a href="#">自転車・アウトドア</a></li>'
+'				</ul>'
+'			</li>'
+'			<li class="D00005"><h3>食品</h3>'
+'				<ul>'
+'					<li><a href="#">料理・調味料</a></li>'
+'					<li><a href="#">菓子・飲料</a></li>'
+'				</ul>'
+'			</li>'
+'		</ul>'
+'	</div><!-- /#snCategory -->');