document.write('	<ul id="memberNav">'
+'		<ul id="storeMember">'
+'			<li id="smLogin"><a href="https://www.muji.net/store/cust/login">ログインはこちら</a></li>'
+'			<li id="smSignUp"><a href="http://www.muji.net/store/pc/user/notice/member.jsp">メンバー登録で500円クーポン！今すぐ無料登録</a></li>'
+'		</ul>'
+'		<ul id="storeNav">'
+'			<li id="snVisitor"><a href="#">はじめての方へ</a></li>'
+'			<li id="stnGuide"><a href="http://faq.muji.net/EokpControl?lang=ja&amp;site=default&amp;event=CE0002&amp;cid=10023">ご利用ガイド</a></li>'
+'		</ul>'
+'		<div id="headerCartBox"><a href="https://www.muji.net/store/cart_param"><span id="cTitle">ショッピングカート</span><span id="cButton">カートを見る</span><span id="cPriceArea"><span id="cOrder">ご注文金額（333点）</span><span id="cPrice" class="price"><span class="num">825,250</span>円</span><!--<p id="cartItem"><img src="http://img.muji.net/img/item/4548718833610_30.jpg"><img src="http://img.muji.net/img/item/4934761133751_30.jpg"><img src="http://img.muji.net/img/item/4548718833610_30.jpg"><img src="http://img.muji.net/img/item/4934761133751_30.jpg"><img src="http://img.muji.net/img/item/4548718833610_30.jpg"></p>--></span></a><!--<div id="CartInfo"><p class="CartInfo_bg"><span>カートに追加しました</span></p></div>--></div><!-- /#headerCartBox -->'
+'		<div id="hSearch">'
+'			<form action="" method="post">'
+'			<ul>'
+'				<li id="sKeyword" class="keyinputoff"><input type="text" id="skey" size="30" maxlength="255" /></li>'
+'				<li id="sCategory"><select id="scat" title="カテゴリーから検索">'
+'						<option value="" selected="selected">全カテゴリーから</option>'
+'						<option value="T10000">婦人ウェア</option>'
+'						<option value="T10001">婦人インナーウェア</option>'
+'						<option value="T10002">紳士ウェア</option>'
+'						<option value="T10003">紳士インナーウェア</option>'
+'					</select></li>'
+'				<li id="sSubmit"><a href="javascript:search()">検索</a></li>'
+'				<li id="sStoreItem"><span class="paren">（</span><label for="sShop"><input type="checkbox" name="sShop" id="sShop" value="" />ネットストア非取扱いを含む全商品から検索</label><span class="paren">）</span></li>'
+'			</ul>'
+'			</form>'
+'		</div><!-- /#hSearch -->'
);
